name: Test SSH Connection to EC2

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the 'main' branch

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Test SSH Connection to EC2
      run: |
        echo "Testing SSH connection to EC2..."
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo "SSH Connection Successful"'
